export const CLIENT_SEARCHING_REQUEST = 'CLIENT_SEARCHING_REQUEST'
export const CLIENT_SEARCHING_SUCCESS = 'CLIENT_SEARCHING_SUCCESS'
export const CLIENT_SEARCHING_ERROR = 'CLIENT_SEARCHING_ERROR'
export const CLIENT_SEARCHING_RESET = 'CLIENT_SEARCHING_RESET'

export const ORDER_CREATING_REQUEST = 'ORDER_CREATING_REQUEST'
export const ORDER_CREATING_SUCCESS = 'ORDER_CREATING_SUCCESS'
export const ORDER_CREATING_ERROR = 'ORDER_CREATING_ERROR'

export const ORDER_UPDATING_REQUEST = 'ORDER_UPDATING_REQUEST'
export const ORDER_UPDATING_SUCCESS = 'ORDER_UPDATING_SUCCESS'
export const ORDER_UPDATING_ERROR = 'ORDER_UPDATING_ERROR'

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST'
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
export const ORDER_LIST_ERROR = 'ORDER_LIST_ERROR'

export const ORDER_DETAIL_REQUEST = 'ORDER_DETAIL_REQUEST'
export const ORDER_DETAIL_SUCCESS = 'ORDER_DETAIL_SUCCESS'
export const EDIT_DIALOG = 'EDIT_DIALOG'
export const ORDER_DETAIL_ERROR = 'ORDER_DETAIL_ERROR'