export const CLIENT_SEARCHING_REQUEST = 'CLIENT_SEARCHING_REQUEST'
export const CLIENT_SEARCHING_SUCCESS = 'CLIENT_SEARCHING_SUCCESS'
export const CLIENT_SEARCHING_ERROR = 'CLIENT_SEARCHING_ERROR'
export const CLIENT_SEARCHING_RESET = 'CLIENT_SEARCHING_RESET'

export const ORDER_CREATING_REQUEST = 'ORDER_CREATING_REQUEST'
export const ORDER_CREATING_SUCCESS = 'ORDER_CREATING_SUCCESS'
export const ORDER_CREATING_ERROR = 'ORDER_CREATING_ERROR'