export const CLIENT_SEARCHING_REQUEST = 'CLIENT_SEARCHING_REQUEST'
export const CLIENT_SEARCHING_SUCCESS = 'CLIENT_SEARCHING_SUCCESS'
export const CLIENT_SEARCHING_ERROR = 'CLIENT_SEARCHING_ERROR'
export const CLIENT_SEARCHING_RESET = 'CLIENT_SEARCHING_RESET'

export const ORDER_CREATING_REQUEST = 'ORDER_CREATING_REQUEST'
export const ORDER_CREATING_SUCCESS = 'ORDER_CREATING_SUCCESS'
export const ORDER_CREATING_ERROR = 'ORDER_CREATING_ERROR'

export const TURN_OFF_DIALOG = 'TURN_OFF_DIALOG'

export const ORDER_UPDATING_REQUEST = 'ORDER_UPDATING_REQUEST'
export const ORDER_UPDATING_SUCCESS = 'ORDER_UPDATING_SUCCESS'
export const ORDER_UPDATING_ERROR = 'ORDER_UPDATING_ERROR'

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST'
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
export const ORDER_LIST_RESET = 'ORDER_LIST_RESET'
export const ORDER_COUNT = 'ORDER_COUNT'
export const ORDER_LIST_ERROR = 'ORDER_LIST_ERROR'

export const ORDER_FINDING_REQUEST = 'ORDER_FINDING_REQUEST'
export const ORDER_FINDING_SUCCESS = 'ORDER_FINDING_SUCCESS'
export const ORDER_FINDING_ERROR = 'ORDER_FINDING_ERROR'

export const ORDER_LIST_SHECDULE_REQUEST = 'ORDER_LIST_SHECDULE_REQUEST'
export const ORDER_LIST_SHECDULE_SUCCESS = 'ORDER_LIST_SHECDULE_SUCCESS'
export const ORDER_LIST_SHECDULE_ERROR = 'ORDER_LIST_SHECDULE_ERROR'

export const ORDER_DETAIL_REQUEST = 'ORDER_DETAIL_REQUEST'
export const ORDER_DETAIL_SUCCESS = 'ORDER_DETAIL_SUCCESS'
export const ORDER_DETAIL_ERROR = 'ORDER_DETAIL_ERROR'

export const TEMPORARY_ORDER_SAVING_REQUEST = 'TEMPORARY_ORDER_SAVING_REQUEST'