export const SESSION = 'SESSION'

export const OPEN_CALL_BOX = 'OPEN_CALL_BOX'
export const OPEN_NUMBER_BOX = 'OPEN_NUMBER_BOX'
export const OPEN_WINDOW = 'OPEN_WINDOW'
export const CLOSE_WINDOW = 'CLOSE_WINDOW'
export const CLOSE_CALL_BOX = 'CLOSE_CALL_BOX'
export const CLOSE_NUMBER_BOX = 'CLOSE_NUMBER_BOX'

export const OUTCOMING_RESPONSE = 'OUTCOMING_RESPONSE'
export const OUTCOMING_REQUEST = 'OUTCOMING_REQUEST'
export const OUTCOMING_END = 'OUTCOMING_END'

export const INCOMING_REQUEST = 'INCOMING_REQUEST'
export const INCOMING_RESPONSE = 'INCOMING_RESPONSE'
export const INCOMING_END = 'INCOMING_END'

export const RESET_DETAIL = 'RESET_DETAIL'