export default {
    NOT_ELIGIBLE                    : "Not eligible",
    NOT_IN_SERVICE_REGION           : "Not in service region",
    NO_PICK_UP                      : "No Pick-up",
    WINDOW_SHOPPING                 : "Window shopping",
    UNABLE_TO_APPRAISE_LIQUIDATED   : "Unable to Appraise/Liquidated",
    DUPLICATE                       : "Duplicate",
    RATE_DISAGREEMENT               : "Rate Disagreement",
    NO_SHOW                         : "No Show",
    MONEY_FROM_DIFFERENT_CHANNEL    : "Money from different channel",
    TERMS_DISAGREEMENT              : "Terms Disagreement",
    SPAM                            : "Spam",
    CALL_AGAIN_LATER                : "Call Again Later",
    WAITING_FOR_MORE_INFO           : "Waiting for more info",
    CONSIDERING                     : "Considering",
    WRONG_INFO                      : "Wrong Info",
    ORDER_CLAIMED                   : "Order Claimed",
    WAITING_FOR_RATE                : "Waiting for Rate",
    APPOINTMENT_1                   : "Appointment #1",
    APPOINTMENT_2                   : "Appointment #2",
    APPOINTMENT_3                   : "Appointment #3",
    APPOINTMENT_4                   : "Appointment #4",
    CUSTOMER_PENDING                : "Customer pending",
    UNCLAIMED                       : "Unclaimed",
    FRAUD                           : "Fraud",
    ACTIVE_CONTRACT                 : "Active Contract",
}