export default {
    NOT_ELIGIBLE                    : {eng: "Not eligible", vi: "Không đủ điều kiện yêu cầu"},
    NOT_IN_SERVICE_REGION           : {eng: "Not in service region", vi: "Tỉnh/thành chưa có dịch vụ"},
    NO_PICK_UP                      : {eng: "No Pick-up", vi: "Không liên lạc được KH"},
    WINDOW_SHOPPING                 : {eng: "Window shopping", vi: "KH thử dịch vụ"},
    UNABLE_TO_APPRAISE_LIQUIDATED   : {eng: "Unable to Appraise/Liquidated", vi: "Không có nơi thanh lý/thẩm định"},
    DUPLICATE                       : {eng: "Duplicate", vi: "Trùng"},
    RATE_DISAGREEMENT               : {eng: "Rate Disagreement", vi: "Không thống nhất về giá."},
    NO_SHOW                         : {eng: "No Show", vi: "Khách hẹn nhưng không lên"},
    MONEY_FROM_DIFFERENT_CHANNEL    : {eng: "Money from different channel", vi: "KH đã xoay được tiền từ nguồn khác."},
    TERMS_DISAGREEMENT              : {eng: "Terms Disagreement", vi: "Không thống nhất về thủ tục"},
    SPAM                            : {eng: "Spam", vi: "Spam dịch vụ"},
    CALL_AGAIN_LATER                : {eng: "Call Again Later", vi: "Gọi lại cho khách hàng."},
    WAITING_FOR_MORE_INFO           : {eng: "Waiting for more info", vi: "Chờ cung cấp thêm thông tin."},
    CONSIDERING                     : {eng: "Considering", vi: "KH đang cân nhắc"},
    WRONG_INFO                      : {eng: "Wrong Info", vi: "Sai thông tin liên lạc"},
    ORDER_CLAIMED                   : {eng: "Order Claimed", vi: "Yêu cầu đã được tiếp nhận"},
    WAITING_FOR_RATE                : {eng: "Waiting for Rate", vi: "Chờ báo giá"},
    APPOINTMENT_1                   : {eng: "Appointment #1", vi: "Khách hẹn lên #1"},
    APPOINTMENT_2                   : {eng: "Appointment #2", vi: "Khách hẹn lên #2"},
    APPOINTMENT_3                   : {eng: "Appointment #3", vi: "Khách hẹn lên #3"},
    APPOINTMENT_4                   : {eng: "Appointment #4", vi: "Khách hẹn lên #4"},
    CUSTOMER_PENDING                : {eng: "Customer pending", vi: "Chờ khách hàng"},
    UNCLAIMED                       : {eng: "Unclaimed", vi: "Yêu cầu chưa được tiếp nhận"},
    FRAUD                           : {eng: "Fraud", vi: "Gian lận/lừa đảo"},
    ACTIVE_CONTRACT                 : {eng: "Active Contract", vi: "Hợp đồng"},
}