export const CLIENT_SEARCHING_REQUEST = 'CLIENT_SEARCHING_REQUEST'
export const CLIENT_SEARCHING_SUCCESS = 'CLIENT_SEARCHING_SUCCESS'
export const CLIENT_SEARCHING_ERROR = 'CLIENT_SEARCHING_ERROR'
export const CLIENT_SEARCHING_RESET = 'CLIENT_SEARCHING_RESET'

export const CLIENT_CREATING_REQUEST = 'CLIENT_CREATING_REQUEST'
export const CLIENT_CREATING_SUCCESS = 'CLIENT_CREATING_SUCCESS'
export const CLIENT_CREATING_ERROR = 'CLIENT_CREATING_ERROR'