
export const CONTRACT_REPAYMENT_SCHEDULE = 'CONTRACT_REPAYMENT_SCHEDULE'
export const CONTRACT_LIST_REQUEST = 'CONTRACT_LIST_REQUEST'
export const CONTRACT_LIST_SUCCESS = 'CONTRACT_LIST_SUCCESS'
export const CONTRACT_LIST_ERROR = 'CONTRACT_LIST_ERROR'

export const CONTRACT_DETAIL_REQUEST = 'CONTRACT_DETAIL_REQUEST'
export const CONTRACT_DETAIL_SUCCESS = 'CONTRACT_DETAIL_SUCCESS'
export const CONTRACT_DETAIL_ERROR = 'CONTRACT_DETAIL_SUCCESS'

export const CONTRACT_FINDING_REQUEST = 'CONTRACT_FINDING_REQUEST'
export const CONTRACT_FINDING_ERROR = 'CONTRACT_FINDING_ERROR'
export const CONTRACT_FINDING_SUCCESS = 'CONTRACT_FINDING_SUCCESS'

export const CONTRACT_DOCUMENT_REQUEST = 'CONTRACT_DOCUMENT_REQUEST'
export const CONTRACT_DOCUMENT_SUCCESS = 'CONTRACT_DOCUMENT_SUCCESS'