
export const CONTRACT_REPAYMENT_SCHEDULE = 'CONTRACT_REPAYMENT_SCHEDULE'
export const CONTRACT_LIST_REQUEST = 'CONTRACT_LIST_REQUEST'
export const CONTRACT_LIST_SUCCESS = 'CONTRACT_LIST_SUCCESS'
export const CONTRACT_LIST_ERROR = 'CONTRACT_LIST_ERROR'