export const SASSET_LIST_REQUEST = 'SASSET_LIST_REQUEST'
export const SASSET_LIST_SUCCESS = 'SASSET_LIST_SUCCESS'
export const SASSET_LIST_ERROR = 'SASSET_LIST_ERROR'

export const CASSET_UPDATING_REQUEST = 'CASSET_UPDATING_REQUEST'
export const CASSET_UPDATING_SUCCESS = 'CASSET_UPDATING_SUCCESS'
export const CASSET_UPDATING_ERROR = 'CASSET_UPDATING_ERROR'